=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GmoPaymentApiClient::FraudDetectionData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GmoPaymentApiClient::FraudDetectionData do
  let(:instance) { GmoPaymentApiClient::FraudDetectionData.new }

  describe 'test an instance of FraudDetectionData' do
    it 'should create an instance of FraudDetectionData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GmoPaymentApiClient::FraudDetectionData)
    end
  end

  describe 'test attribute "user_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "identity_doc_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PASSPORT", "TAXSTATEMENT"])
      # validator.allowable_values.each do |value|
      #   expect { instance.identity_doc_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "identity_doc_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_corporation_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_phone"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NEXT_DAY_OVERNIGHT", "TWO_DAY_SERVICE", "THREE_DAY_SERVICE", "LOWEST_COST", "CARRIER_DESIGNATED_BY_CUSTOMER", "ELECTRONIC_DELIVERY", "GROUND", "INTERNATIONAL", "MILITARY", "STORE_PICKUP", "SAME_DAY_SERVICE", "OTHER", "PUDO", "EXPEDITED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.shipping_method = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "shipping_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_tracking_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_comment"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_salutation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "device_information"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "repeater"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user_registration_elapsed_days"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "promotion_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "gift_card_message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "gift_card_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ANNIVERSARY", "APRIL_FOOLS_DAY", "BABY_SHOWER", "BIRTHDAY", "BOSSES_DAY", "CELEBRATE_FALL", "CHINESE_NEW_YEAR", "CHRISTMAS", "CONGRATULATIONS", "EASTER", "FATHERS_DAY", "GRADUATION", "GRANDPARENTS_DAY", "HALLOWEEN", "HANUKKAH", "HOLIDAY", "INDEPENDENCE_DAY", "KWANZAA", "MOTHERS_DAY", "NEW_YEARS_DAY", "OTHER", "PASSOVER", "SEASONS_GREETINGS", "SECRETARYS_DAY", "ST_PATRICKS_DAY", "SWEETEST_DAY", "THANKSGIVING", "VALENTINES_DAY", "WEDDING"])
      # validator.allowable_values.each do |value|
      #   expect { instance.gift_card_type = value }.not_to raise_error
      # end
    end
  end

end
