=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GmoPaymentApiClient::Mulpay
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GmoPaymentApiClient::Mulpay do
  let(:instance) { GmoPaymentApiClient::Mulpay.new }

  describe 'test an instance of Mulpay' do
    it 'should create an instance of Mulpay' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GmoPaymentApiClient::Mulpay)
    end
  end

end
