=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GmoPaymentApiClient::RedirectInformation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GmoPaymentApiClient::RedirectInformation do
  let(:instance) { GmoPaymentApiClient::RedirectInformation.new }

  describe 'test an instance of RedirectInformation' do
    it 'should create an instance of RedirectInformation' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GmoPaymentApiClient::RedirectInformation)
    end
  end

  describe 'test attribute "redirect_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "http_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["GET", "POST"])
      # validator.allowable_values.each do |value|
      #   expect { instance.http_method = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "redirect_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["TDS2", "WALLET_CHARGE", "WALLET_AUTHORIZE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.redirect_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "redirect_parameters"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
