=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GmoPaymentApiClient::MemberApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MemberApi' do
  before do
    # run before each test
    @api_instance = GmoPaymentApiClient::MemberApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MemberApi' do
    it 'should create an instance of MemberApi' do
      expect(@api_instance).to be_instance_of(GmoPaymentApiClient::MemberApi)
    end
  end

  # unit tests for member_create
  # ID登録
  # 会員を登録するためのAPIです。 
  # @param member_create_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 冪等キー   UUIDv4に則った書式でリクエスト毎にユニークとなる最大36桁の値。   詳細は[冪等処理](#tag/idempotence)を参照ください。 
  # @return [MemberCreateResponse]
  describe 'member_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for member_delete
  # 全削除
  # 会員情報を削除するためのAPIです。   Pay払いの認証情報も含まれます。   一度削除した会員ID、認証情報は二度と利用できないため、ご注意ください。 
  # @param member_delete_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 冪等キー   UUIDv4に則った書式でリクエスト毎にユニークとなる最大36桁の値。   詳細は[冪等処理](#tag/idempotence)を参照ください。 
  # @return [MemberDeleteResponse]
  describe 'member_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for member_delete_item
  # 認証情報削除
  # 会員に登録されている情報を削除するためのAPIです。   楽天ペイ(オンライン決済)V2ではご利用いただけません。 
  # @param member_delete_item_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 冪等キー   UUIDv4に則った書式でリクエスト毎にユニークとなる最大36桁の値。   詳細は[冪等処理](#tag/idempotence)を参照ください。 
  # @return [MemberDeleteItem201Response]
  describe 'member_delete_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for member_inquiry
  # 照会
  # 会員情報を照会するためのAPIです。 
  # @param member_inquiry_request 
  # @param [Hash] opts the optional parameters
  # @return [MemberInquiryResponse]
  describe 'member_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
