=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GmoPaymentApiClient::CashApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CashApi' do
  before do
    # run before each test
    @api_instance = GmoPaymentApiClient::CashApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CashApi' do
    it 'should create an instance of CashApi' do
      expect(@api_instance).to be_instance_of(GmoPaymentApiClient::CashApi)
    end
  end

  # unit tests for cash_charge
  # 支払い番号発行
  # コンビニ決済や銀行振込などの現金払いでのお支払い時に利用するAPIです。   支払いの結果は、非同期で加盟店様がリクエスト時に設定した[Webhook URLにHTTPメソッド&#x60;POST&#x60;で通知](#tag/events/operation/cashWebhook)します。 
  # @param cash_charge_request どの現金払いを利用するかは&#x60;cashInformation.cashType&#x60;で設定します。 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 冪等キー   UUIDv4に則った書式でリクエスト毎にユニークとなる最大36桁の値。   詳細は[冪等処理](#tag/idempotence)を参照ください。 
  # @return [CashChargeResponse]
  describe 'cash_charge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
