=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GmoPaymentApiClient::OrderApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrderApi' do
  before do
    # run before each test
    @api_instance = GmoPaymentApiClient::OrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderApi' do
    it 'should create an instance of OrderApi' do
      expect(@api_instance).to be_instance_of(GmoPaymentApiClient::OrderApi)
    end
  end

  # unit tests for order_cancel
  # キャンセル
  # 支払いを取り消すためのAPIです。 
  # @param order_cancel_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 冪等キー   UUIDv4に則った書式でリクエスト毎にユニークとなる最大36桁の値。   詳細は[冪等処理](#tag/idempotence)を参照ください。 
  # @return [OrderCancel201Response]
  describe 'order_cancel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for order_capture
  # 確定
  # 決済確定のためのAPIです。 
  # @param order_capture_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 冪等キー   UUIDv4に則った書式でリクエスト毎にユニークとなる最大36桁の値。   詳細は[冪等処理](#tag/idempotence)を参照ください。 
  # @return [OrderCapture201Response]
  describe 'order_capture test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for order_inquiry
  # 照会
  # 取引を照会するためのAPIです。   accessIdとorderIdのどちらかは必ず設定してください。   accessIdとorderIdの両方を設定した場合は両方に一致する取引情報を返却します。 
  # @param order_inquiry_request 
  # @param [Hash] opts the optional parameters
  # @return [OrderInquiryResponse]
  describe 'order_inquiry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for order_update
  # 金額変更
  # すでに支払い済みの取引の金額を変更します。   決済手段と支払い状態により実行できる処理が異なります。   クレジットカードの場合は、当サービス内部で取消と再オーソリ(信用照会)の処理を実施します。   お客様の信用状態によっては、再オーソリ(信用照会)が失敗する場合があり、その場合は取消は無効となり金額変更APIを呼び出す前の状態に戻ります。   クレジットカードは同じ金額を設定して呼び出すことで、仮売上状態の延長が可能です。  |||仮売上&lt;br&gt;の減額|仮売上&lt;br&gt;の増額|実売上&lt;br&gt;の減額|実売上&lt;br&gt;の増額|即時売上&lt;br&gt;の減額|即時売上&lt;br&gt;の増額| |:-------|:------------|:-:|:-:|:-:|:-:|:-:|:-:| |クレカ払い|クレカ     | 〇 | 〇 | 〇 | 〇 | 〇 | 〇 | |         |Google Pay | 〇 | 〇 | 〇 | 〇 | 〇 | 〇 | |         |Apple Pay  | △&lt;sup&gt;*1&lt;/sup&gt; | △&lt;sup&gt;*1&lt;/sup&gt; | △&lt;sup&gt;*1&lt;/sup&gt; | △&lt;sup&gt;*1&lt;/sup&gt; | △&lt;sup&gt;*1&lt;/sup&gt; | △&lt;sup&gt;*1&lt;/sup&gt; | |Pay払い  |PayPay     | × | × | 〇 | × | 〇 | × | |         |d払い      | × | × | 〇 | △&lt;sup&gt;*2&lt;/sup&gt; | 〇 | △&lt;sup&gt;*2&lt;/sup&gt; | |         |楽天ペイ(オンライン決済)V2 | 〇 | 〇 | 〇 | 〇 | 〇 | 〇 | |         |Amazon Pay V2 | 〇 | 〇 | 〇 | × | 〇 | × | |         |au PAY(ネット支払い)アプリ方式  | 〇 | 〇 | 〇 | × | 〇 | × | |         |メルペイ    | × | × | 〇 | × | 〇 | × | |現金払い  |コンビニ   | - | - | - | - | - | - | |         |Pay-easy   | - | - | - | - | - | - | |         |銀行振込    | - | - | - | - | - | - |  *1：Visaブランドのカードは増額・減額ができません。   *2：減額した取引に限り、元取引金額までの決済金額の増額ができます。 
  # @param order_update_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 冪等キー   UUIDv4に則った書式でリクエスト毎にユニークとなる最大36桁の値。   詳細は[冪等処理](#tag/idempotence)を参照ください。 
  # @return [OrderUpdate201Response]
  describe 'order_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
