=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GmoPaymentApiClient::TokenApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TokenApi' do
  before do
    # run before each test
    @api_instance = GmoPaymentApiClient::TokenApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TokenApi' do
    it 'should create an instance of TokenApi' do
      expect(@api_instance).to be_instance_of(GmoPaymentApiClient::TokenApi)
    end
  end

  # unit tests for token
  # アクセストークン発行
  # アクセストークン方式の認証に利用するアクセストークンを発行するために呼び出すAPIです。   認証の詳細は[APIの認証](#tag/authentication)を参照ください。 
  # @param grant_type グラントタイプ   &#x60;client_credentials&#x60;を設定してください。 
  # @param scope スコープ &#x60;openapi&#x60;を設定してください。 
  # @param [Hash] opts the optional parameters
  # @return [TokenResponse]
  describe 'token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
