=begin
#PGマルチペイメントサービス OpenAPIタイプ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'date'
require 'time'

module GmoPaymentApiClient
  # 不正検知オプション情報
  class FraudDetectionOptions
    # 審査タイプ
    attr_accessor :screening_type

    # オーソリ中断閾値   当パラメーターを設定した場合はオーソリ(信用照会)前に不正審査を実施し、審査結果が設定した閾値以上である場合はオーソリ(信用照会)を中断します。   例) `CHALLENGE`を設定した場合、審査結果が`CHALLENGE`または`DENY`の際はオーソリを中断します。 
    attr_accessor :stop_authorization_threshold

    # 非同期モード   `true`を設定した場合は不正審査を非同期で実行します。 この際レスポンスに審査結果は含まれませんので、任意のタイミングで[取引照会API(/order/inquiry)](#tag/order/operation/orderInquiry)を実行し取得してください。 
    attr_accessor :async_mode

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'screening_type' => :'screeningType',
        :'stop_authorization_threshold' => :'stopAuthorizationThreshold',
        :'async_mode' => :'asyncMode'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'screening_type' => :'String',
        :'stop_authorization_threshold' => :'String',
        :'async_mode' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GmoPaymentApiClient::FraudDetectionOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GmoPaymentApiClient::FraudDetectionOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'screening_type')
        self.screening_type = attributes[:'screening_type']
      else
        self.screening_type = nil
      end

      if attributes.key?(:'stop_authorization_threshold')
        self.stop_authorization_threshold = attributes[:'stop_authorization_threshold']
      end

      if attributes.key?(:'async_mode')
        self.async_mode = attributes[:'async_mode']
      else
        self.async_mode = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @screening_type.nil?
        invalid_properties.push('invalid value for "screening_type", screening_type cannot be nil.')
      end

      pattern = Regexp.new(/^DENY|CHALLENGE$/)
      if !@stop_authorization_threshold.nil? && @stop_authorization_threshold !~ pattern
        invalid_properties.push("invalid value for \"stop_authorization_threshold\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @screening_type.nil?
      screening_type_validator = EnumAttributeValidator.new('String', ["RED_SHIELD"])
      return false unless screening_type_validator.valid?(@screening_type)
      return false if !@stop_authorization_threshold.nil? && @stop_authorization_threshold !~ Regexp.new(/^DENY|CHALLENGE$/)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] screening_type Object to be assigned
    def screening_type=(screening_type)
      validator = EnumAttributeValidator.new('String', ["RED_SHIELD"])
      unless validator.valid?(screening_type)
        fail ArgumentError, "invalid value for \"screening_type\", must be one of #{validator.allowable_values}."
      end
      @screening_type = screening_type
    end

    # Custom attribute writer method with validation
    # @param [Object] stop_authorization_threshold Value to be assigned
    def stop_authorization_threshold=(stop_authorization_threshold)
      if stop_authorization_threshold.nil?
        fail ArgumentError, 'stop_authorization_threshold cannot be nil'
      end

      pattern = Regexp.new(/^DENY|CHALLENGE$/)
      if stop_authorization_threshold !~ pattern
        fail ArgumentError, "invalid value for \"stop_authorization_threshold\", must conform to the pattern #{pattern}."
      end

      @stop_authorization_threshold = stop_authorization_threshold
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          screening_type == o.screening_type &&
          stop_authorization_threshold == o.stop_authorization_threshold &&
          async_mode == o.async_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [screening_type, stop_authorization_threshold, async_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = GmoPaymentApiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
